[project]
name = "maaautonaruto"
version = "1.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "json-with-comments>=1.2.10",
    "loguru>=0.7.3",
    "maafw>=5.2.6",
    "pillow>=12.0.0",
]
