name: mirrorchyan_release_note

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
  release:
    types: [edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MaaAutoNaruto
          version_name: ${{ inputs.tag }}

          owner: duorua
          repo: narutomobile
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
